Api-edu-frane-main/src/Entity/IpsColleges.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use Doctrine\ORM\Mapping as ORM;

use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\GetCollection;
use App\Controller\GetCollegesDataParUAIController;
use App\Controller\GetCollegesParLieux;
use App\Repository\IpsCollegesRepository;

#[ORM\Entity(repositoryClass: IpsCollegesRepository::class)]
#[ApiResource(
    operations: [
        new Post(
            uriTemplate: 'admin/ips_collegess'
        ),
        new Delete(
            uriTemplate: 'admin/ips_collegess/{id}'
        ),
        new Patch(
            uriTemplate: 'admin/ips_collegess/{id}'
        ),
        new Get(
            uriTemplate: 'user/ips_collegess/{id}'
        ),
        new GetCollection(
            uriTemplate: 'user/ips_collegess'
        ),
        new Get(
            uriTemplate: '/industrie_du_futur/{tagregion}/{ville}',
            requirements: [
                'tagregion' => '\d+',
                'ville' => '\w+',
            ],
            controller: GetCollegesParLieux::class,
            read: false,
            output: false,
            description: 'Récupère un MontantInvest par son type',
            name: 'get_by_title',

        ),
        new Get(
            uriTemplate: '/getCollegesUai/{id}',
            requirements: [
                'id' => '\d+',
            ],
            controller: GetCollegesDataParUAIController::class,
            read: false,
            output: false,
            description: 'Récupère les infos du colleges selon uai',
            name: 'get_by_uai',
        ),
    ]
)]
class IpsColleges
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 9)]
    private ?string $rentree_scolaire = null;

    #[ORM\Column(length: 20)]
    private ?string $academie = null;

    #[ORM\Column(length: 3)]
    private ?string $code_du_departement = null;

    #[ORM\Column(length: 25)]
    private ?string $departement = null;

    #[ORM\Column(length: 8)]
    private ?string $uai = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_de_l_etablissment = null;

    #[ORM\Column(length: 10)]
    private ?string $code_insee_de_la_commune = null;

    #[ORM\Column(length: 40)]
    private ?string $nom_de_la_commune = null;

    #[ORM\Column(length: 20)]
    private ?string $secteur = null;

    #[ORM\Column]
    private ?float $ips = null;

    #[ORM\Column(nullable: true)]
    private ?float $ecart_type_de_l_ips = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRentreeScolaire(): ?string
    {
        return $this->rentree_scolaire;
    }

    public function setRentreeScolaire(string $rentree_scolaire): static
    {
        $this->rentree_scolaire = $rentree_scolaire;

        return $this;
    }

    public function getAcademie(): ?string
    {
        return $this->academie;
    }

    public function setAcademie(string $academie): static
    {
        $this->academie = $academie;

        return $this;
    }

    public function getCodeDuDepartement(): ?string
    {
        return $this->code_du_departement;
    }

    public function setCodeDuDepartement(string $code_du_departement): static
    {
        $this->code_du_departement = $code_du_departement;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): static
    {
        $this->departement = $departement;

        return $this;
    }

    public function getUai(): ?string
    {
        return $this->uai;
    }

    public function setUai(string $uai): static
    {
        $this->uai = $uai;

        return $this;
    }

    public function getNomDeLEtablissment(): ?string
    {
        return $this->nom_de_l_etablissment;
    }

    public function setNomDeLEtablissment(string $nom_de_l_etablissment): static
    {
        $this->nom_de_l_etablissment = $nom_de_l_etablissment;

        return $this;
    }

    public function getCodeInseeDeLaCommune(): ?string
    {
        return $this->code_insee_de_la_commune;
    }

    public function setCodeInseeDeLaCommune(string $code_insee_de_la_commune): static
    {
        $this->code_insee_de_la_commune = $code_insee_de_la_commune;

        return $this;
    }

    public function getNomDeLaCommune(): ?string
    {
        return $this->nom_de_la_commune;
    }

    public function setNomDeLaCommune(string $nom_de_la_commune): static
    {
        $this->nom_de_la_commune = $nom_de_la_commune;

        return $this;
    }

    public function getSecteur(): ?string
    {
        return $this->secteur;
    }

    public function setSecteur(string $secteur): static
    {
        $this->secteur = $secteur;

        return $this;
    }

    public function getIps(): ?float
    {
        return $this->ips;
    }

    public function setIps(float $ips): static
    {
        $this->ips = $ips;

        return $this;
    }

    public function getEcartTypeDeLIps(): ?float
    {
        return $this->ecart_type_de_l_ips;
    }

    public function setEcartTypeDeLIps(float $ecart_type_de_l_ips): static
    {
        $this->ecart_type_de_l_ips = $ecart_type_de_l_ips;

        return $this;
    }
}

Api-edu-frane-main/src/Form/IpsCollegesType.php
<?php

namespace App\Form;

use App\Entity\IpsColleges;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IpsCollegesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rentree_scolaire', TextType::class, ['attr' => ['maxlength' => 9]])
            ->add('academie', TextType::class, ['attr' => ['maxlength' => 20]])
            ->add('code_du_departement', TextType::class, ['attr' => ['maxlength' => 3]])
            ->add('departement', TextType::class, ['attr' => ['maxlength' => 25]])
            ->add('uai', TextType::class, ['attr' => ['maxlength' => 8]])
            ->add('nom_de_l_etablissment', TextType::class, ['attr' => ['maxlength' => 255]])
            ->add('code_insee_de_la_commune', TextType::class, ['attr' => ['maxlength' => 10]])
            ->add('nom_de_la_commune', TextType::class, ['attr' => ['maxlength' => 40]])
            ->add('secteur', TextType::class, ['attr' => ['maxlength' => 20]])
            ->add('ips', NumberType::class)
            ->add('ecart_type_de_l_ips', NumberType::class, ['required' => false]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => IpsColleges::class,
        ]);
    }
}

Api-edu-frane-main/src/Controller/IpsCollegesController.php
<?php

namespace App\Controller;

use App\Entity\IpsColleges;
use App\Form\IpsCollegesType;
use App\Repository\IpsCollegesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Knp\Component\Pager\PaginatorInterface;

#[IsGranted('ROLE_ADMIN')]
#[Route('/ips')]
class IpsCollegesController extends AbstractController
{
    #[Route('/', name: 'app_ips_colleges_index', methods: ['GET'])]
    public function index(
        IpsCollegesRepository $ipsCollegesRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        if ($request->query->has('search') && $request->query->get('search') != '') {
            $donnees = $ipsCollegesRepository->findBy(
                ['nom_de_la_commune' => strtoupper($request->query->get('search'))]
            );
        } else {
            $donnees = $ipsCollegesRepository->findAll();
        }

        $pagination = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer
            $request->query->getInt('page', 1), // Numéro de page à afficher, 1 par défaut
            15 // Nombre d'éléments par page
        );

        return $this->render('ips_colleges/index.html.twig', [
            'ips_colleges' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_ips_colleges_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {


        $ipsCollege = new IpsColleges();
        $form = $this->createForm(IpsCollegesType::class, $ipsCollege);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($ipsCollege);
            $entityManager->flush();

            return $this->redirectToRoute('app_ips_colleges_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ips_colleges/new.html.twig', [
            'ips_college' => $ipsCollege,
            'form' => $form,
            'type' => 'new'
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ips_colleges_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, IpsColleges $ipsCollege, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(IpsCollegesType::class, $ipsCollege);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_ips_colleges_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ips_colleges/new.html.twig', [
            'ips_college' => $ipsCollege,
            'form' => $form,
            'type' => 'edit'
        ]);
    }

    #[Route('/{id}', name: 'app_ips_colleges_delete', methods: ['POST'])]
    public function delete(Request $request, IpsColleges $ipsCollege, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $ipsCollege->getId(), $request->request->get('_token'))) {
            $entityManager->remove($ipsCollege);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_ips_colleges_index', [], Response::HTTP_SEE_OTHER);
    }
}

Api-edu-frane-main/templates/ips_colleges/_delete_form.html.twig
<form method="post" action="{{ path('app_ips_colleges_delete', {'id': ips_college.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ips_college.id) }}">
    <button class="btn secondary-btn" style="width:fit-content">Supprimer</button>
</form>

Api-edu-frane-main/templates/ips_colleges/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Api-edu-frane-main/templates/ips_colleges/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit IpsColleges{% endblock %}

{% block body %}
    <h1>Edit IpsColleges</h1>

    {{ include('ips_colleges/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_ips_colleges_index') }}">back to list</a>

    {{ include('ips_colleges/_delete_form.html.twig') }}
{% endblock %}

Api-edu-frane-main/templates/ips_colleges/index.html.twig
{% extends 'base.html.twig' %}
{% import 'partials/_indexCrud.html.twig' as tableau %}

{% block title %}IpsColleges index{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/tables.css">
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script src="/assets/js/search.js" defer></script>
{% endblock %}

{% block body %}
    {% set row %}
            <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Rentree_scolaire</th>
                            <th>Academie</th>
                            <th>Code_du_departement</th>
                            <th>Departement</th>
                            <th>Uai</th>
                            <th>Nom_de_l_etablissment</th>
                            <th>Code_insee_de_la_commune</th>
                            <th>Nom_de_la_commune</th>
                            <th>Secteur</th>
                            <th>Ips</th>
                            <th>Ecart_type_de_l_ips</th>
                            <th>Liens</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for ips_college in ips_colleges %}
                        <tr>
                            <td>{{ ips_college.id }}</td>
                            <td>{{ ips_college.rentreeScolaire }}</td>
                            <td>{{ ips_college.academie }}</td>
                            <td>{{ ips_college.codeDuDepartement }}</td>
                            <td>{{ ips_college.departement }}</td>
                            <td>{{ ips_college.uai }}</td>
                            <td>{{ ips_college.nomDeLEtablissment }}</td>
                            <td>{{ ips_college.codeInseeDeLaCommune }}</td>
                            <td>{{ ips_college.nomDeLaCommune }}</td>
                            <td>{{ ips_college.secteur }}</td>
                            <td>{{ ips_college.ips }}</td>
                            <td>{{ ips_college.ecartTypeDeLIps }}</td>
                            <td>
                                <a href="{{ path('app_ips_colleges_edit', {'id': ips_college.id}) }}" class="link">Modifier</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="13">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
        {% endset %}

    {{ tableau.tableau(row, ips_colleges, 'app_ips_colleges_new', 'Nom_de_la_commune') }}
{% endblock %}

Api-edu-frane-main/templates/ips_colleges/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}IpsColleges{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/create.css">
{% endblock %}

{% block body %}
    {% if type == 'new'%}
        <h1>Créer une entrée</h1>
    {% else %}
        <h1>Modifier une entrée</h1>
    {% endif %}
    <div class="sep"></div>

    {{ form_start(form) }}
        <div>
            <div class="field">
                {{ form_label(form.rentree_scolaire) }}
                {{ form_widget(form.rentree_scolaire) }}
                {{ form_errors(form.rentree_scolaire) }}
            </div>
            <div class="field">
                {{ form_label(form.academie) }}
                {{ form_widget(form.academie) }}
                {{ form_errors(form.academie) }}
            </div>
            <div class="field">
                {{ form_label(form.code_du_departement) }}
                {{ form_widget(form.code_du_departement) }}
                {{ form_errors(form.code_du_departement) }}
            </div>
            <div class="field">
                {{ form_label(form.departement) }}
                {{ form_widget(form.departement) }}
                {{ form_errors(form.departement) }}
            </div>
            <div class="field">
                {{ form_label(form.uai) }}
                {{ form_widget(form.uai) }}
            </div>
            <div class="field">
                {{ form_label(form.nom_de_l_etablissment) }}
                {{ form_widget(form.nom_de_l_etablissment) }}
                {{ form_errors(form.nom_de_l_etablissment) }}
            </div>
        </div>
        <div>
            <div class="field">
                {{ form_label(form.code_insee_de_la_commune) }}
                {{ form_widget(form.code_insee_de_la_commune) }}
                {{ form_errors(form.code_insee_de_la_commune) }}
            </div>
            <div class="field">
                {{ form_label(form.nom_de_la_commune) }}
                {{ form_widget(form.nom_de_la_commune) }}
                {{ form_errors(form.nom_de_la_commune) }}
            </div>
            <div class="field">
                {{ form_label(form.secteur) }}
                {{ form_widget(form.secteur) }}
                {{ form_errors(form.secteur) }}
            </div>
            <div class="field">
                {{ form_label(form.ips) }}
                {{ form_widget(form.ips) }}
                {{ form_errors(form.ips) }}
            </div>
            <div class="field">
                {{ form_label(form.ecart_type_de_l_ips) }}
                {{ form_widget(form.ecart_type_de_l_ips) }}
                {{ form_errors(form.ecart_type_de_l_ips) }}
            </div>
        </div>

        <div class="actions">
        {% if type == 'new'%}
            <button class="btn main-btn" style="width:fit-content">{{ button_label|default('Créer une nouvelle entrée') }}</button>
        {% else %}
            <button class="btn main-btn" style="width:fit-content">{{ button_label|default('Modifier les informations') }}</button>
            {{ include('ips_colleges/_delete_form.html.twig') }}
            {{ form_rest(form) }}
        {% endif %} 
            <a href="{{ path('app_ips_colleges_index') }}" style="width:fit-content" class="btn third-btn">Retourner à la liste</a>
        </div>
    {{ form_end(form) }}

    
{% endblock %}