Api-edu-frane-main/src/Entity/DNB2018.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use Doctrine\ORM\Mapping as ORM;

use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\GetCollection;
use App\Controller\GetDNB2018ParUAIController;
use App\Repository\DNB2018Repository;

#[ORM\Entity(repositoryClass: DNB2018Repository::class)]
#[ApiResource(
    operations: [
        new Post(
            uriTemplate: 'admin/dnb2018s'
        ),
        new Delete(
            uriTemplate: 'admin/dnb2018s/{id}'
        ),
        new Patch(
            uriTemplate: 'admin/dnb2018s/{id}'
        ),
        new Get(
            uriTemplate: 'user/dnb2018s/{id}'
        ),
        new GetCollection(
            uriTemplate: 'user/dnb2018s'
        ),
        new Get(
            uriTemplate: '/getDNB2018result/{id}',
            requirements: [
                'id' => '\d+',
            ],
            controller: GetDNB2018ParUAIController::class,
            read: false,
            output: false,
            description: 'Récupère les infos du des résultat du DNB 2018 par colleges selon uai',
            name: 'get_DNB_by_uai',
        ),
    ]
)]
class DNB2018
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $session = null;

    #[ORM\Column(length: 10)]
    private ?string $numero_etablissement = null;

    #[ORM\Column(length: 30)]
    private ?string $denomination_principale = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $patronyme = null;

    #[ORM\Column(length: 15)]
    private ?string $secteur_denseignement = null;

    #[ORM\Column(length: 5)]
    private ?string $commune = null;

    #[ORM\Column(length: 40)]
    private ?string $libelle_commune = null;

    #[ORM\Column(length: 3)]
    private ?string $code_departement = null;

    #[ORM\Column(length: 25)]
    private ?string $libelle_departement = null;

    #[ORM\Column]
    private ?int $code_academie = null;

    #[ORM\Column(length: 20)]
    private ?string $libelle_academie = null;

    #[ORM\Column]
    private ?int $code_region = null;

    #[ORM\Column(length: 30)]
    private ?string $libelle_region = null;

    #[ORM\Column(length: 3)]
    private ?string $inscrits = null;

    #[ORM\Column(length: 3)]
    private ?string $presents = null;

    #[ORM\Column(length: 3)]
    private ?string $admis = null;

    #[ORM\Column(length: 3)]
    private ?string $admis_sans_mention = null;

    #[ORM\Column(length: 10)]
    private ?string $taux_de_reussite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSession(): ?int
    {
        return $this->session;
    }

    public function setSession(int $session): static
    {
        $this->session = $session;

        return $this;
    }

    public function getNumeroEtablissement(): ?string
    {
        return $this->numero_etablissement;
    }

    public function setNumeroEtablissement(string $numero_etablissement): static
    {
        $this->numero_etablissement = $numero_etablissement;

        return $this;
    }

    public function getDenominationPrincipale(): ?string
    {
        return $this->denomination_principale;
    }

    public function setDenominationPrincipale(string $denomination_principale): static
    {
        $this->denomination_principale = $denomination_principale;

        return $this;
    }

    public function getPatronyme(): ?string
    {
        return $this->patronyme;
    }

    public function setPatronyme(?string $patronyme): static
    {
        $this->patronyme = $patronyme;

        return $this;
    }

    public function getSecteurDenseignement(): ?string
    {
        return $this->secteur_denseignement;
    }

    public function setSecteurDenseignement(string $secteur_denseignement): static
    {
        $this->secteur_denseignement = $secteur_denseignement;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): static
    {
        $this->commune = $commune;

        return $this;
    }

    public function getLibelleCommune(): ?string
    {
        return $this->libelle_commune;
    }

    public function setLibelleCommune(string $libelle_commune): static
    {
        $this->libelle_commune = $libelle_commune;

        return $this;
    }

    public function getCodeDepartement(): ?string
    {
        return $this->code_departement;
    }

    public function setCodeDepartement(string $code_departement): static
    {
        $this->code_departement = $code_departement;

        return $this;
    }

    public function getLibelleDepartement(): ?string
    {
        return $this->libelle_departement;
    }

    public function setLibelleDepartement(string $libelle_departement): static
    {
        $this->libelle_departement = $libelle_departement;

        return $this;
    }

    public function getCodeAcademie(): ?int
    {
        return $this->code_academie;
    }

    public function setCodeAcademie(int $code_academie): static
    {
        $this->code_academie = $code_academie;

        return $this;
    }

    public function getLibelleAcademie(): ?string
    {
        return $this->libelle_academie;
    }

    public function setLibelleAcademie(string $libelle_academie): static
    {
        $this->libelle_academie = $libelle_academie;

        return $this;
    }

    public function getCodeRegion(): ?int
    {
        return $this->code_region;
    }

    public function setCodeRegion(int $code_region): static
    {
        $this->code_region = $code_region;

        return $this;
    }

    public function getLibelleRegion(): ?string
    {
        return $this->libelle_region;
    }

    public function setLibelleRegion(string $libelle_region): static
    {
        $this->libelle_region = $libelle_region;

        return $this;
    }

    public function getInscrits(): ?string
    {
        return $this->inscrits;
    }

    public function setInscrits(string $inscrits): static
    {
        $this->inscrits = $inscrits;

        return $this;
    }

    public function getPresents(): ?string
    {
        return $this->presents;
    }

    public function setPresents(string $presents): static
    {
        $this->presents = $presents;

        return $this;
    }

    public function getAdmis(): ?string
    {
        return $this->admis;
    }

    public function setAdmis(string $admis): static
    {
        $this->admis = $admis;

        return $this;
    }

    public function getAdmisSansMention(): ?string
    {
        return $this->admis_sans_mention;
    }

    public function setAdmisSansMention(string $admis_sans_mention): static
    {
        $this->admis_sans_mention = $admis_sans_mention;

        return $this;
    }

    public function getTauxDeReussite(): ?string
    {
        return $this->taux_de_reussite;
    }

    public function setTauxDeReussite(string $taux_de_reussite): static
    {
        $this->taux_de_reussite = $taux_de_reussite;

        return $this;
    }
}

Api-edu-frane-main/src/Form/DNB2018Type.php
<?php

namespace App\Form;

use App\Entity\DNB2018;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DNB2018Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('session')
            ->add('numero_etablissement')
            ->add('denomination_principale')
            ->add('patronyme')
            ->add('secteur_denseignement')
            ->add('commune')
            ->add('libelle_commune')
            ->add('code_departement')
            ->add('libelle_departement')
            ->add('code_academie')
            ->add('libelle_academie')
            ->add('code_region')
            ->add('libelle_region')
            ->add('inscrits')
            ->add('presents')
            ->add('admis')
            ->add('admis_sans_mention')
            ->add('taux_de_reussite')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DNB2018::class,
        ]);
    }
}

Api-edu-frane-main/src/Controller/DNB2018Controller.php
<?php

namespace App\Controller;

use App\Entity\DNB2018;
use App\Form\DNB2018Type;
use App\Repository\DNB2018Repository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_ADMIN')]
#[Route('/dnb2018')]
class DNB2018Controller extends AbstractController
{
    #[Route('/', name: 'app_d_n_b2018_index', methods: ['GET'])]
    public function index(
        DNB2018Repository $dNB2018Repository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        if ($request->query->has('search') && $request->query->get('search') != '') {
            $donnees = $dNB2018Repository->findBy(
                ['libelle_commune' => strtoupper($request->query->get('search'))]
            );
        } else {
            $donnees = $dNB2018Repository->findAll();
        }

        $pagination = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1),
            15
        );

        return $this->render('dnb2018/index.html.twig', [
            'dnb2018s' => $pagination
        ]);
    }

    #[Route('/new', name: 'app_d_n_b2018_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $dNB2018 = new DNB2018();
        $form = $this->createForm(DNB2018Type::class, $dNB2018);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($dNB2018);
            $entityManager->flush();

            return $this->redirectToRoute('app_d_n_b2018_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('dnb2018/new.html.twig', [
            'd_n_b2018' => $dNB2018,
            'form' => $form,
            'type' => 'new'
        ]);
    }

    #[Route('/{id}', name: 'app_d_n_b2018_show', methods: ['GET'])]
    public function show(DNB2018 $dNB2018): Response
    {
        return $this->render('dnb2018/show.html.twig', [
            'd_n_b2018' => $dNB2018,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_d_n_b2018_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, DNB2018 $dNB2018, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DNB2018Type::class, $dNB2018);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_d_n_b2018_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('dnb2018/new.html.twig', [
            'd_n_b2018' => $dNB2018,
            'form' => $form,
            'type' => 'edit'
        ]);
    }

    #[Route('/{id}', name: 'app_d_n_b2018_delete', methods: ['POST'])]
    public function delete(Request $request, DNB2018 $dNB2018, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $dNB2018->getId(), $request->request->get('_token'))) {
            $entityManager->remove($dNB2018);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_d_n_b2018_index', [], Response::HTTP_SEE_OTHER);
    }
}

Api-edu-frane-main/templates/dnb2018/_delete_form.html.twig
<form method="post" action="{{ path('app_d_n_b2018_delete', {'id': d_n_b2018.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ d_n_b2018.id) }}">
    <button class="btn">Delete</button>
</form>

Api-edu-frane-main/templates/dnb2018/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Api-edu-frane-main/templates/dnb2018/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit DNB2018{% endblock %}

{% block body %}
    <h1>Edit DNB2018</h1>

    {{ include('dnb2018/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_d_n_b2018_index') }}">back to list</a>

    {{ include('dnb2018/_delete_form.html.twig') }}
{% endblock %}

Api-edu-frane-main/templates/dnb2018/index.html.twig
{% extends 'base.html.twig' %}
{% import 'partials/_indexCrud.html.twig' as tableau %}


{% block title %}DNB2018 index{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/tables.css">
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script src="/assets/js/search.js" defer></script>
{% endblock %}

{% block body %}
    {% set row %}
        <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Session</th>
                <th>Numero_etablissement</th>
                <th>Denomination_principale</th>
                <th>Patronyme</th>
                <th>Secteur_denseignement</th>
                <th>Commune</th>
                <th>Libelle_commune</th>
                <th>Code_departement</th>
                <th>Libelle_departement</th>
                <th>Code_academie</th>
                <th>Libelle_academie</th>
                <th>Code_region</th>
                <th>Libelle_region</th>
                <th>Inscrits</th>
                <th>Presents</th>
                <th>Admis</th>
                <th>Admis_sans_mention</th>
                <th>Taux_de_reussite</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dnb2018 in dnb2018s %}
            <tr>
                <td>{{ dnb2018.id }}</td>
                <td>{{ dnb2018.session }}</td>
                <td>{{ dnb2018.numeroEtablissement }}</td>
                <td>{{ dnb2018.denominationPrincipale }}</td>
                <td>{{ dnb2018.patronyme }}</td>
                <td>{{ dnb2018.secteurDenseignement }}</td>
                <td>{{ dnb2018.commune }}</td>
                <td>{{ dnb2018.libelleCommune }}</td>
                <td>{{ dnb2018.codeDepartement }}</td>
                <td>{{ dnb2018.libelleDepartement }}</td>
                <td>{{ dnb2018.codeAcademie }}</td>
                <td>{{ dnb2018.libelleAcademie }}</td>
                <td>{{ dnb2018.codeRegion }}</td>
                <td>{{ dnb2018.libelleRegion }}</td>
                <td>{{ dnb2018.inscrits }}</td>
                <td>{{ dnb2018.presents }}</td>
                <td>{{ dnb2018.admis }}</td>
                <td>{{ dnb2018.admisSansMention }}</td>
                <td>{{ dnb2018.tauxDeReussite }}</td>
                <td>
                    <a href="{{ path('app_d_n_b2018_edit', {'id': dnb2018.id}) }}" class="link">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% endset %}

    {{ tableau.tableau(row, dnb2018s, 'app_d_n_b2018_new', 'Libelle_commune') }}
{% endblock %}

Api-edu-frane-main/templates/dnb2018/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}DNB 2018{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/create.css">
{% endblock %}

{% block body %}
    {% if type == 'new'%}
        <h1>Créer une entrée</h1>
    {% else %}
        <h1>Modifier une entrée</h1>
    {% endif %}
    <div class="sep"></div>

    {{ form_start(form) }}
        <div>
            <div class="field">
                {{ form_label(form.session) }}
                {{ form_widget(form.session) }}
                {{ form_errors(form.session) }}
            </div>
            <div class="field">
                {{ form_label(form.numero_etablissement) }}
                {{ form_widget(form.numero_etablissement) }}
                {{ form_errors(form.numero_etablissement) }}
            </div>
            <div class="field">
                {{ form_label(form.denomination_principale) }}
                {{ form_widget(form.denomination_principale) }}
                {{ form_errors(form.denomination_principale) }}
            </div>
            <div class="field">
                {{ form_label(form.patronyme) }}
                {{ form_widget(form.patronyme) }}
                {{ form_errors(form.patronyme) }}
            </div>
            <div class="field">
                {{ form_label(form.secteur_denseignement) }}
                {{ form_widget(form.secteur_denseignement) }}
            </div>
            <div class="field">
                {{ form_label(form.commune) }}
                {{ form_widget(form.commune) }}
                {{ form_errors(form.commune) }}
            </div>
            <div class="field">
                {{ form_label(form.code_academie) }}
                {{ form_widget(form.code_academie) }}
                {{ form_errors(form.code_academie) }}
            </div>
            <div class="field">
                {{ form_label(form.libelle_academie) }}
                {{ form_widget(form.libelle_academie) }}
                {{ form_errors(form.libelle_academie) }}
            </div>
            <div class="field">
                {{ form_label(form.libelle_commune) }}
                {{ form_widget(form.libelle_commune) }}
                {{ form_errors(form.libelle_commune) }}
            </div>
        </div>
        <div>
            <div class="field">
                {{ form_label(form.code_departement) }}
                {{ form_widget(form.code_departement) }}
                {{ form_errors(form.code_departement) }}
            </div>
            <div class="field">
                {{ form_label(form.libelle_departement) }}
                {{ form_widget(form.libelle_departement) }}
                {{ form_errors(form.libelle_departement) }}
            </div>
            <div class="field">
                {{ form_label(form.code_region) }}
                {{ form_widget(form.code_region) }}
                {{ form_errors(form.code_region) }}
            </div>
            <div class="field">
                {{ form_label(form.libelle_region) }}
                {{ form_widget(form.libelle_region) }}
                {{ form_errors(form.libelle_region) }}
            </div>
            <div class="field">
                {{ form_label(form.inscrits) }}
                {{ form_widget(form.inscrits) }}
                {{ form_errors(form.inscrits) }}
            </div>
            <div class="field">
                {{ form_label(form.presents) }}
                {{ form_widget(form.presents) }}
                {{ form_errors(form.presents) }}
            </div>
            <div class="field">
                {{ form_label(form.admis) }}
                {{ form_widget(form.admis) }}
                {{ form_errors(form.admis) }}
            </div>
            <div class="field">
                {{ form_label(form.admis_sans_mention) }}
                {{ form_widget(form.admis_sans_mention) }}
                {{ form_errors(form.admis_sans_mention) }}
            </div>
            <div class="field">
                {{ form_label(form.taux_de_reussite) }}
                {{ form_widget(form.taux_de_reussite) }}
                {{ form_errors(form.taux_de_reussite) }}
            </div>
        </div>

        <div class="actions">
        {% if type == 'new'%}
            <button class="btn main-btn" style="width:fit-content">{{ button_label|default('Créer une nouvelle entrée') }}</button>
        {% else %}
            <button class="btn main-btn" style="width:fit-content">{{ button_label|default('Modifier les informations') }}</button>
            {{ include('dnb2018/_delete_form.html.twig') }}
            {{ form_rest(form) }}
        {% endif %} 
            <a href="{{ path('app_d_n_b2018_index') }}" style="width:fit-content" class="btn third-btn">Retourner à la liste</a>
        </div>
    {{ form_end(form) }}

    
{% endblock %}

Api-edu-frane-main/templates/dnb2018/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}DNB2018{% endblock %}

{% block body %}
    <h1>DNB2018</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ d_n_b2018.id }}</td>
            </tr>
            <tr>
                <th>Session</th>
                <td>{{ d_n_b2018.session }}</td>
            </tr>
            <tr>
                <th>Numero_etablissement</th>
                <td>{{ d_n_b2018.numeroEtablissement }}</td>
            </tr>
            <tr>
                <th>Denomination_principale</th>
                <td>{{ d_n_b2018.denominationPrincipale }}</td>
            </tr>
            <tr>
                <th>Patronyme</th>
                <td>{{ d_n_b2018.patronyme }}</td>
            </tr>
            <tr>
                <th>Secteur_denseignement</th>
                <td>{{ d_n_b2018.secteurDenseignement }}</td>
            </tr>
            <tr>
                <th>Commune</th>
                <td>{{ d_n_b2018.commune }}</td>
            </tr>
            <tr>
                <th>Libelle_commune</th>
                <td>{{ d_n_b2018.libelleCommune }}</td>
            </tr>
            <tr>
                <th>Code_departement</th>
                <td>{{ d_n_b2018.codeDepartement }}</td>
            </tr>
            <tr>
                <th>Libelle_departement</th>
                <td>{{ d_n_b2018.libelleDepartement }}</td>
            </tr>
            <tr>
                <th>Code_academie</th>
                <td>{{ d_n_b2018.codeAcademie }}</td>
            </tr>
            <tr>
                <th>Libelle_academie</th>
                <td>{{ d_n_b2018.libelleAcademie }}</td>
            </tr>
            <tr>
                <th>Code_region</th>
                <td>{{ d_n_b2018.codeRegion }}</td>
            </tr>
            <tr>
                <th>Libelle_region</th>
                <td>{{ d_n_b2018.libelleRegion }}</td>
            </tr>
            <tr>
                <th>Inscrits</th>
                <td>{{ d_n_b2018.inscrits }}</td>
            </tr>
            <tr>
                <th>Presents</th>
                <td>{{ d_n_b2018.presents }}</td>
            </tr>
            <tr>
                <th>Admis</th>
                <td>{{ d_n_b2018.admis }}</td>
            </tr>
            <tr>
                <th>Admis_sans_mention</th>
                <td>{{ d_n_b2018.admisSansMention }}</td>
            </tr>
            <tr>
                <th>Taux_de_reussite</th>
                <td>{{ d_n_b2018.tauxDeReussite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_d_n_b2018_index') }}">back to list</a>

    <a href="{{ path('app_d_n_b2018_edit', {'id': d_n_b2018.id}) }}">edit</a>

    {{ include('dnb2018/_delete_form.html.twig') }}
{% endblock %}